# Generated by Django 6.0 on 2025-12-16 06:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoaxPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('KEYWORD', 'Kata Kunci'), ('PHRASE', 'Frasa'), ('PATTERN', 'Pola Kalimat'), ('SOURCE', 'Sumber Terindikasi')], max_length=50, verbose_name='Jenis Pola')),
                ('pattern_content', models.TextField(verbose_name='Konten Pola')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('severity', models.IntegerField(choices=[(1, 'Rendah'), (2, 'Sedang'), (3, 'Tinggi')], default=2, verbose_name='Tingkat Keparahan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pola Hoax',
                'verbose_name_plural': 'Pola-pola Hoax',
            },
        ),
        migrations.CreateModel(
            name='DetectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Teks Berita')),
                ('result', models.CharField(choices=[('HOAX', 'Hoax'), ('VALID', 'Valid'), ('UNCERTAIN', 'Perlu Verifikasi')], max_length=20, verbose_name='Hasil Deteksi')),
                ('confidence', models.FloatField(help_text='Persentase keyakinan model (0-1)', verbose_name='Tingkat Keyakinan')),
                ('hoax_probability', models.FloatField(default=0.0, verbose_name='Probabilitas Hoax')),
                ('valid_probability', models.FloatField(default=0.0, verbose_name='Probabilitas Valid')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='URL Sumber')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata Tambahan')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Waktu Deteksi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Alamat IP')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Terverifikasi Manual')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Verifikasi')),
                ('verification_notes', models.TextField(blank=True, verbose_name='Catatan Verifikasi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_history', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'History Deteksi',
                'verbose_name_plural': 'History Deteksi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(verbose_name='Hasil Benar?')),
                ('comments', models.TextField(blank=True, verbose_name='Komentar')),
                ('suggested_label', models.CharField(blank=True, choices=[('HOAX', 'Hoax'), ('VALID', 'Valid'), ('UNCERTAIN', 'Perlu Verifikasi')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='detection_app.detectionhistory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
            },
        ),
        migrations.AddIndex(
            model_name='detectionhistory',
            index=models.Index(fields=['created_at'], name='detection_a_created_0d6454_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionhistory',
            index=models.Index(fields=['result'], name='detection_a_result_02fbde_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionhistory',
            index=models.Index(fields=['user', 'created_at'], name='detection_a_user_id_24eb02_idx'),
        ),
    ]
